MemoryCards/Models/DeckBox.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MemoryCards.Models
{
    public class DeckBox : TimeStamp
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Отсутствует название")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длина названия должна быть от 3 до 50 символов")]
        public string Title { get; set; }
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длина описания должна быть от 3 до 50 символов")]
        public string Description { get; set; }
                
        public string UserId { get; set; }
        public User User { get; set; }

        public string DeckBoxcColor { get; set; }
        public int Rating { get; set; }
        public bool Private { get; set; }
        public Image Image { get; set; }
        public List<Deck> Decks { get; set;}
        public DeckBox()
        {
            this.CreatedAt = DateTime.Now;
            this.UpdatedAt = DateTime.Now;
        }
        public int LearnedWords()
        {
            int countCards = 0;
            foreach (var item in Decks)
            {
                if (item.CountLearnCards != 0)
                {
                    countCards += 1;
                }
            }
            return countCards;
        }
           public int CountWords()
           {
            int countWords = 0;
            foreach (var item in Decks)
            {
                countWords += item.Cards.Count;
            }
                return countWords;
            }   
    }
}

MemoryCards/Controllers/DeckBoxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MemoryCards;
using MemoryCards.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using MemoryCards.Solid;
using MemoryCards.ViewModels;
using System.Globalization;
using Microsoft.Extensions.Localization;
using System.Threading;

namespace MemoryCards.Controllers
{
    [Authorize]
     
    public class DeckBoxesController : Controller
    {
        private readonly MemoryContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<DecksController> _localizer;

        public DeckBoxesController(MemoryContext context, UserManager<User> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: DeckBoxes
        public async Task<IActionResult> Index()
        {          
            string userId =  _userManager.GetUserId(User);
            List<DeckBox> memoryContext = 
                await _context.DeckBoxes.Include("User")
                .Where(d => d.UserId == userId).Include(p=> p.Image)
                .Include(p=>p.Decks).ThenInclude(p=>p.Cards)
                .ThenInclude(p=>p.Image).OrderBy(p=>p.Rating).ToListAsync();
            return View(memoryContext);
        }

        // GET: DeckBoxes/Create
        public IActionResult Create()
        {             
            return View();
        }
        // POST: DeckBoxes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Rating,Private,CreatedAt,DeckBoxcColor")] DeckBox deckBox, IFormFile imageDb)
        {
            if (ModelState.IsValid)
            {             
                Image dbImage = new Image();
                if (imageDb != null)
                {
                    string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                    var filename = ImageAbillities.UploadImage(imageDb, folderPath);

                    dbImage.DeckBoxImageName = filename;
                    dbImage.DeckBoxId = deckBox.Id;
                    deckBox.Image = dbImage;
                    deckBox.DeckBoxcColor = null;
                }
                if(deckBox.DeckBoxcColor == null)
                {
                    deckBox.DeckBoxcColor = "#999999";
                }
                User user = await _userManager.GetUserAsync(User);
                List<DeckBox> deckBoxes = _context.DeckBoxes.Where(d => d.UserId == user.Id).ToList();
                deckBox.Rating = deckBoxes.Count + 1;
                deckBox.UserId = user.Id;
                _context.Add(deckBox);
                await _context.SaveChangesAsync();
                CreateDecksDefault(deckBox);
                return RedirectToAction(nameof(Index));

            }
            return View(deckBox);
        }

        // GET: DeckBoxes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string userId = _userManager.GetUserId(User);
            var deckBox = await _context.DeckBoxes.Include(p=>p.Image).FirstOrDefaultAsync(p=>p.Id == id && p.UserId == userId);
            if (deckBox == null)
            {
                return View("AccessError"); 
            }
 
            return View(deckBox);
        }

        // POST: DeckBoxes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,UserId,Rating,Private,UpdatedAt,DeckBoxcColor,CreatedAt,Image")]
        DeckBox deckBox, IFormFile Imagedb)
        {
            if (id != deckBox.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Image imaged = await _context.Images.FirstOrDefaultAsync(p => p.DeckBoxId == deckBox.Id);                
         
                try
                {
                    if (Imagedb != null && imaged!=null)
                    {
                        List<DeckBox> deckBoxes = _context.DeckBoxes
                        .Where(p => p.Image.DeckBoxImageName == imaged.DeckBoxImageName
                        && p.Id != deckBox.Id).ToList();
                        if (imaged!= null && deckBoxes.Count == 0)
                        {
                            string folderPathLstImg = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                            ImageAbillities.DeleteImage(imaged.DeckBoxImageName, folderPathLstImg);
                        }
                        string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                        var filename = ImageAbillities.UploadImage(Imagedb, folderPath);
                        deckBox.DeckBoxcColor = null;
                        Image dbImage = new Image();
                        dbImage.DeckBoxId = deckBox.Id;
                        dbImage.DeckBoxImageName = filename;
                        deckBox.Image = dbImage;
                        _context.Remove(imaged);
                    }
                    else if(Imagedb!=null && imaged == null)
                    {
                        string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                        var filename = ImageAbillities.UploadImage(Imagedb, folderPath);
                        Image dbImage = new Image();
                        dbImage.DeckBoxId = deckBox.Id;
                        dbImage.DeckBoxImageName = filename;
                        deckBox.Image = dbImage;
                        deckBox.DeckBoxcColor = null;
                    }
                   else if (Imagedb == null && imaged!=null && deckBox.DeckBoxcColor!=null)
                    {
                     List<DeckBox> deckBoxes = _context.DeckBoxes
                     .Where(p => p.Image.DeckBoxImageName == imaged.DeckBoxImageName
                     && p.Id != deckBox.Id).ToList();
                        if (imaged != null && deckBoxes.Count == 0)
                           {
                               string folderPathLstImg = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                               ImageAbillities.DeleteImage(imaged.DeckBoxImageName, folderPathLstImg);
                            }
                        deckBox.Image = null;
                        if (imaged != null)
                            _context.Images.Remove(imaged);                  
                    }                  
                    _context.Update(deckBox);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeckBoxExists(deckBox.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
              
                return RedirectToAction(nameof(Index));
            }

            return View(deckBox);
        }


        public async Task<IActionResult> Delete(int id)
        {
            DeckBox deckbox = _context.DeckBoxes.Include(p => p.Image).FirstOrDefault(p => p.Id == id);
            if (deckbox.Image != null)
            {
                List<DeckBox> deckBoxes = _context.DeckBoxes.Where(p => p.Image.DeckBoxImageName == deckbox.Image.DeckBoxImageName
             && p.Id != deckbox.Id).ToList();
                if (deckbox.Image.DeckBoxImageName != null && deckBoxes.Count == 0)
                {
                    string folderPathLstImg = Path.Combine(_webHostEnvironment.WebRootPath, "images", "deckBox_images");
                    ImageAbillities.DeleteImage(deckbox.Image.DeckBoxImageName, folderPathLstImg);
                    Image image = _context.Images.FirstOrDefault(p => p.DeckBoxId == deckbox.Id);
                    _context.Remove(image);
                    await _context.SaveChangesAsync();
                }
            }

            List<Deck> decks = await _context.Decks.Include(p => p.Cards).ThenInclude(p => p.Image).Where(p => p.DeckBoxId == id).ToListAsync();
            List<Card> cards = new List<Card>();
            foreach (var c in decks)
            {
                if (c.Cards != null)
                {
                    cards.AddRange(c.Cards);
                }
            }
            if (cards != null)
            {
                foreach (var c in cards)
                {
                    List<Card> cardsfordelete = new List<Card>();
                    if (c.Image != null)
                    {
                        cardsfordelete = _context.Cards.Where(p => p.Image.CardImageName == c.Image.CardImageName && p.Id != c.Id).ToList();
                    }
                    if (c.Image != null && cardsfordelete.Count == 0)
                    {

MemoryCards/Controllers/DecksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MemoryCards.Models;
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Localization;
namespace MemoryCards.Controllers
{
    [Authorize]
    public class DecksController : Controller
    {
        private readonly MemoryContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IStringLocalizer<DecksController> _localizer;

        public DecksController(MemoryContext context, IStringLocalizer<DecksController> localizer, UserManager<User> userManager)
        {
            _context = context;
            _localizer = localizer;
            _userManager = userManager;

        }

        public IActionResult Index(int? Id)
        {
            string userId =  _userManager.GetUserId(User);
            var deckBox = _context.DeckBoxes.FirstOrDefault(p => p.Id == Id);
            var deck = _context.Decks
                .Include(c => c.Cards)
                .Where(p => p.DeckBoxId == deckBox.Id && deckBox.UserId == userId)
                .OrderBy(c => c.RepeatDay);
            if(deck.Count()==0)
                return View("AccessError");
            return View(deck);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string userId = _userManager.GetUserId(User);
            var deck = await _context.Decks.FirstOrDefaultAsync(p=>p.Id==id && p.DeckBox.UserId == userId);
            
            if (deck == null)
            {
                return View("AccessError");
            }
            return View(deck);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RepeatDay,DeckBoxId,CreatedAt,UpdatedAt, LastSendMsgDate")] Deck deck)
        {
            if (id != deck.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var deckBox = _context.DeckBoxes
                        .AsNoTracking()
                        .Include(d => d.Decks)
                        .FirstOrDefault(p => p.Id == deck.DeckBoxId);
                    var check = deckBox.Decks.FirstOrDefault(c => c.RepeatDay == deck.RepeatDay);

                    if (check == null)
                    {
                        deck.LastSendMsgDate = DateTime.Now.AddDays(deck.RepeatDay);
                        _context.Update(deck);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                          TempData["deckerror"]=_localizer["deckError"]; 
                        return View(deck);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeckExists(deck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { Id = deck.DeckBoxId });
            }
            return View(deck);
        }

        private bool DeckExists(int id)
        {
            return _context.Decks.Any(e => e.Id == id);
        }
    }
}

MemoryCards/Views/DeckBoxes/Create.cshtml
@model MemoryCards.Models.DeckBox

@{
    ViewData["Title"] = Localizer["createtitle"];
}

<h1>@Localizer["createtitle"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.Image.ImageFile" />
            <input type="hidden" asp-for="@Model.Image.DeckBoxImageName" />
            <input type="hidden" asp-for="@Model.Image" />
            <div class="group">
                <input asp-for="Title" type="text" required class="input" autocomplete="off" autofocus>
                <span class="highlight"></span>
                <span class="bar"></span>
                <span asp-validation-for="Title" id="validTitle" class="text-danger"></span>
                <label class="label">@Localizer["title"]</label>
            </div>
            <div class="form-group">
                <label class="desc">@Localizer["description"]</label>
                <textarea asp-for="Description" class="form-control" rows="3" id="exampleFormControlTextarea1"></textarea>
                <span asp-validation-for="Description" id="validDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p class="imageName">@Localizer["imagedeckbox"]</p>
                <label name="imageDb" class="file">
                    <input type="file" name="imageDb" id="file" aria-label="File browser example" autofocus>
                    <span name="imageDb" class="file-custom"></span>
                </label>
            </div>
            <div class="form-group" id="d">
                <div class="color-wrapper">
                    <p>@Localizer["colordeckbox"]</p>
                    <input type="text" asp-for="DeckBoxcColor" id="pickcolor" class="call-picker" autocomplete="off" autofocus>
                    <div class="color-holder call-picker"></div>
                    <div class="color-picker" id="color-picker" style="display: none"></div>
                </div>
            </div>
            <div class="form-group" id="switch_pozit">
                <p class="priv">@Localizer["private"]</p>
                <label class="switch">
                    <input asp-for="Private" type="checkbox" class="switch_button" value="True" autofocus>
                    <span class="slider"></span>
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["create"]" class="btn btn-light" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a type="button" asp-action="Index" class="btn btn-light">@Localizer["back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MemoryCards/Views/DeckBoxes/DeckboxView.cshtml
@model MemoryCards.Models.DeckBox

@{
    ViewData["Title"] = Localizer["title"];
}
 
<link rel="stylesheet" href="~/css/style.css">
<link rel="stylesheet" href="~/css/site.css">
<div class="p-3" id="fh5co-work">
    <h2 class="lead"><a asp-action="UserProfile" asp-controller="Account" asp-route-id="@Model.UserId">@Model.User.Login </a>@Localizer["sharedit"]</h2>
    @if (Model.Image == null)
    {
        <div class="col-md-4 text-center animate-box " data-id="@Model.Id" style="padding-top: 22px;">
            <a class="work" asp-controller="Home" asp-action="Deck" asp-route-id="@Model.Id">
                <div class="work-grid" style="background-color:@Model.DeckBoxcColor">
                    <div class="inner">
                        <div class="desc" style="text-align:center;max-width:300px;">
                            <h3>@Model.Title <br /> - <br /></h3>
                            <h5 style="word-wrap: break-word">@Model.Description</h5>
                            <p class="cat">@Localizer["countwords"]<strong> @Model.CountWords()</strong></p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="btn btn-secondary" id="share" asp-controller="DeckBoxes" asp-action="GetDeckBox" asp-route-id="@Model.Id">
                @Localizer["takeitforyourself"]
            </a>
        </div>
    }
    else
    {
        <div class="col-md-4 text-center animate-box" data-id="@Model.Id" style="padding-top:22px;">
            <a class="work" asp-controller="Home" asp-action="Deck" asp-route-id="@Model.Id">
                <div class="work-grid" style="background-image: url('../../images/deckBox_images/@Model.Image.DeckBoxImageName');">
                    <div class="inner">
                        <div class="desc" style="text-align:center; max-width:300px;">
                            <h3>@Model.Title <br /> - <br /></h3>
                            <h5 style="word-wrap: break-word">@Model.Description</h5>
                            <p class="cat">@Localizer["countwords"]<strong> @Model.CountWords()</strong></p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="btn btn-secondary" id="share" asp-controller="DeckBoxes" asp-action="GetDeckBox" asp-route-id="@Model.Id">
                @Localizer["takeitforyourself"]
            </a>
        </div>
    }
</div>

MemoryCards/Views/DeckBoxes/Index.cshtml
@model IEnumerable<MemoryCards.Models.DeckBox>

@{
    ViewData["Title"] = Localizer["indextitle"];
}
<link rel="stylesheet" href="~/css/animate.css">
<link rel="stylesheet" href="~/css/icomoon.css">
<link rel="stylesheet" href="~/css/style.css">

<h1 class="text-center">@Localizer["indextitle"]</h1>
<link href="~/css/indexDeckboxcss.css" rel="stylesheet" />
<hr />
<div id="elements-container">
    <div id="fh5co-work">
        <div class="container">
            <button type="button" class="btn btn-light" style="display:none" id="save-ordering">@Localizer["savechanges"]</button>
            <div class="row" id="dragable-elements-list">
                <div class="col-lg-4 col-md-6 image-grid-item" style="padding-top:26px;">
                    <div class="card text-center">
                        <div class="card-body" style="height: 291px; padding-top:20px; ">
                            <h1 class="text-center" style="line-height:50%;padding-top:75px;"><a class="text-decoration-none" id="createDeckbox" asp-action="Create">+</a></h1>
                            <footer class="blockquote-footer text-center">
                                @Localizer["createdeckbox"]
                            </footer>
                        </div>
                    </div>
                </div>
                @foreach (var item in Model)
                {
                    if (item.Image == null)
                    {
                        <div class="col-md-4 text-center animate-box  draggable-element" data-id="@item.Id" style="padding-top: 22px;">
                            <a class="work" asp-controller="Decks" asp-action="Index" asp-route-id="@item.Id">
                                <div class="work-grid" style="background-color:@item.DeckBoxcColor">
                                    <div class="inner">
                                        <div class="desc" style="text-align:center;max-width:300px;">
                                            <h3>@item.Title <br /> - <br /></h3>
                                            <h5 style="word-wrap: break-word">@item.Description</h5>
                                            <span class="cat">@Localizer["learnedwords"]<strong> @item.LearnedWords()</strong></span>
                                            <p>-</p>
                                            <p class="cat">@Localizer["countwords"]<strong> @item.CountWords()</strong></p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <div class="privating">
                                @if (item.Private)
                                {
                                    <h3>@Localizer["private"]</h3>
                                }
                                else
                                {
                                    <h3>@Localizer["public"]</h3>
                                }
                            </div>
                            <div class="card-body" style="padding-bottom:13px;">
                                <a href="#" onclick="GenerationUrl('@item.Id')" class="btn btn-outline-primary" name="@item.Id" id="share" title="Share">@Localizer["share"]</a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-light editDeckbox" title="Edit">@Localizer["edit"]</a>
                                <a class="btn btn-light deleteDeckbox" onclick="return confirm('@Localizer["deletejs"]')" asp-action="Delete" asp-route-id="@item.Id" title="Delete">@Localizer["delete"]</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="col-lg-4 col-md-6 text-center animate-box  draggable-element" data-id="@item.Id" style="padding-top:22px;">
                            <a class="work" asp-controller="Decks" asp-action="Index" asp-route-id="@item.Id">
                                <div class="work-grid" style="backGround-image: url('../../images/deckBox_images/@item.Image.DeckBoxImageName');">
                                    <div class="inner">
                                        <div class="desc" style="text-align:center; max-width:300px;">
                                            <h3>@item.Title <br /> - <br /></h3>
                                            <h5 style="word-wrap: break-word">@item.Description</h5>
                                            <span class="cat">@Localizer["learnedwords"]<strong> @item.LearnedWords()</strong></span>
                                            <p>-</p>
                                            <p class="cat">@Localizer["countwords"]<strong> @item.CountWords()</strong></p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <div class="privating">
                                @if (item.Private)
                                {
                                    <h3>@Localizer["private"]</h3>
                                }
                                else
                                {
                                    <h3>@Localizer["public"]</h3>
                                }
                            </div>
                            <div class="card-body">
                                <a href="#" onclick="GenerationUrl('@item.Id')" class="btn btn-outline-primary" id="share" name="@item.Id" title="Share">@Localizer["share"]</a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-light editDeckbox" title="Edit">@Localizer["edit"]</a>
                                <a class="btn btn-light deleteDeckbox" onclick="return confirm('@Localizer["deletejs"]')" asp-action="Delete" asp-route-id="@item.Id" title="Delete">@Localizer["delete"]</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.draggable-element').arrangeable();
        });
        $("body").on('DOMSubtreeModified', "#dragable-elements-list", function () {
            $('#save-ordering').show();
        });
        $('#save-ordering').on('click', function () {
            var objectArray = [];
            $(".draggable-element").each(function (index) {

                var obj = {
                    DeckBoxId: $(this).data('id'),
                    NewRating: index + 1
                }
                objectArray.push(obj);
            });
            console.log(objectArray);
            var postData = JSON.stringify(objectArray);
              $.ajax({
                url: '@Url.Action("RatingSort", "DeckBoxes")',
                type: 'POST',
                contentType: 'application/json',
                dataType: 'json',
                data: postData,
                success: function (data, status, xhr) {
                    $('#save-ordering').hide();
                },
                error: function (jqXhr, textStatus, errormessage) {
                },
            });
        })
    </script>
    <script>
        function GenerationUrl(deckboxid) {
            $.ajax({
                url: '@Url.Action("Base64Encode", "DeckBoxes")',
                type: 'POST',
                data: { 'deckboxid': deckboxid},
                success: function (data, status, xhr) {
                var result = JSON.parse(data.value);
                    alert(result.URL);
                },
                error: function (jqXhr, textStatus, errormessage) {
                },
            });
        }
    </script>
}