MemoryCards/Models/Card.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MemoryCards.Models
{
    public class Card : TimeStamp
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Обязательное поле")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длина названия должна быть от 3 до 50 символов")]
        public string Word { get; set; }

        [Required(ErrorMessage = "Обязательное поле")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "Длина определения должна быть от 3 до 150 символов")]
        public string Defination { get; set; }

        public int DeckId { get; set; }
        public Deck Deck { get; set; }
        [Required(ErrorMessage = "Обязательное поле")]
        [StringLength(150, MinimumLength = 1, ErrorMessage = "Длина названия должна быть от 1 до 150 символов")]
        public string UseExample { get; set; }    
        public int? ShowCount { get; set; }
        public DateTime? MoveDate { get; set; }
        public Image Image { get; set; }
        public Card()
        {
            this.CreatedAt = DateTime.Now;
            this.UpdatedAt = DateTime.Now;
        }
    }
}

MemoryCards/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MemoryCards;
using MemoryCards.Models;
using MemoryCards.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using MemoryCards.Solid;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace MemoryCards.Controllers
{
    [Authorize]
    public class CardsController : Controller
    {
        private readonly MemoryContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<User> _userManager;
        public CardsController(MemoryContext context, IWebHostEnvironment webHostEnvironment, UserManager<User> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Cards
        public async Task<IActionResult> Index(int? Id, int? Nextcardid)
        {
            string userId = _userManager.GetUserId(User);
            List<Card> cards = await _context.Cards.Include("Deck")
                .Include(p=>p.Deck.DeckBox)
                .Include(p=>p.Image)
                .Where(c => c.DeckId == Id && c.Deck.DeckBox.UserId==userId)
                .OrderBy(c => c.MoveDate).ToListAsync();

            CardDeckViewModel cardDeckViewModel = new CardDeckViewModel
            {
                Cards =  cards,
                DeckId = Id,
                Deck = _context.Decks.Include(d=>d.DeckBox).FirstOrDefault(p => p.Id == Id && p.DeckBox.UserId == userId)
            };
            if (cardDeckViewModel.Deck == null)
                return View("AccessError");
            if (Nextcardid != null)
                ViewBag.Nextid = Nextcardid;
            return View(cardDeckViewModel);

        }

        // GET: Cards/Create
        public IActionResult Create(int? id)
        {
            string userId = _userManager.GetUserId(User);
            CardDeckViewModel cardDeckViewModel = new CardDeckViewModel
            {
                Deck = _context.Decks.Include(d => d.DeckBox).FirstOrDefault(p => p.Id == id && p.DeckBox.UserId == userId),
                card = new Card(),
            };
            if (cardDeckViewModel.Deck == null)
                return View("AccessError"); 
            return View(cardDeckViewModel);
        }

        // POST: Cards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Word,Defination,DeckId,UseExample,CreatedAt,UpdatedAt,Image")] Card card, int DeckId)
        {
            if (ModelState.IsValid)
            {
                if (card.Image != null)
                {
                    string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "card_images");
                    var filename = ImageAbillities.UploadImage(card.Image.ImageFile, folderPath);
                    card.Image.CardImageName = filename;
                }
                card.DeckId = DeckId;
                card.ShowCount = 0;
                card.MoveDate = DateTime.Now;
                _context.Add(card);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { Id = DeckId });
            }
            return View(card);
        }

        public async Task<IActionResult> Know(int Id)
        {
            Card card = _context.Cards.FirstOrDefault(c => c.Id == Id); //карточка опреде
            Deck deck = _context.Decks.FirstOrDefault(d => d.Cards.Contains(card));// из опреде коробки
            List<Card> cards = await _context.Cards.Where(c => c.DeckId == deck.Id)
                .OrderBy(c => c.MoveDate).ToListAsync();

            var next = (from x in cards where x.MoveDate > card.MoveDate orderby x.MoveDate ascending select x).FirstOrDefault();
            if (next == null)
            {
                next = (from x in cards where x.MoveDate < card.MoveDate orderby x.MoveDate ascending select x).FirstOrDefault();
            }

            if (deck == null)
            {
                return View();
            }
            else
            {
                DeckBox deckBox = _context.DeckBoxes.Include(p => p.Decks).FirstOrDefault(db => db.Decks.Contains(deck));//из опред словаря
                deckBox.Decks = deckBox.Decks.OrderBy(p => p.RepeatDay).ToList();//сортиров репеат дай
                Deck nextDeck = deckBox.Decks.FirstOrDefault(p => p.RepeatDay > deck.RepeatDay); //отсортров репеат дау по большен у определн словаря больше определен коробки
                if (nextDeck != null)
                {
                    card.DeckId = nextDeck.Id;
                    card.Deck = nextDeck;
                    card.ShowCount += 1;
                    card.MoveDate = DateTime.Now;
                    if (card.ShowCount == 3)
                    {
                        deck.CountLearnCards += 1;
                    }
                    _context.Update(card);
                    await _context.SaveChangesAsync();
                }
            }
            if (next?.Id == null)
            {
                return RedirectToAction(nameof(Index), new { Id = deck.Id });
            }
            else
            {
                return RedirectToAction(nameof(Index), new { Id = deck.Id, Nextcardid = next.Id });
            }
        }

        public async Task<IActionResult> DontKnow(int Id)
        {
            Card card = _context.Cards.FirstOrDefault(c => c.Id == Id);
            Deck deck = _context.Decks.FirstOrDefault(d => d.Cards.Contains(card));
            List<Card> cards = await _context.Cards.Where(c => c.DeckId == deck.Id)
                .OrderBy(c => c.MoveDate).ToListAsync();

            var next = (from x in cards where x.MoveDate > card.MoveDate orderby x.MoveDate ascending select x).FirstOrDefault();
            if (next == null)
            {
                next = (from x in cards where x.MoveDate < card.MoveDate orderby x.MoveDate ascending select x).FirstOrDefault();
            }

            DeckBox deckBox = _context.DeckBoxes.Include(p => p.Decks).FirstOrDefault(db => db.Decks.Contains(deck));
            deckBox.Decks = deckBox.Decks.OrderByDescending(p => p.RepeatDay).ToList();
     
             
           Deck prevDeck = deckBox.Decks.FirstOrDefault(p=>p.RepeatDay<deck.RepeatDay);
           
            if (prevDeck != null)
            {
                card.DeckId = prevDeck.Id;
                card.Deck = prevDeck;
                card.MoveDate = DateTime.Now;
                _context.Update(card);
                await _context.SaveChangesAsync();
            }

            if (next?.Id == null)
            {
                return RedirectToAction(nameof(Index), new { Id = deck.Id });
            }
            else
            {
                return RedirectToAction(nameof(Index), new { Id = deck.Id, Nextcardid = next.Id });
            }
        }
        // GET: Cards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string userId = _userManager.GetUserId(User);
            var card = await _context.Cards.Include(p=>p.Deck).Include(p=>p.Deck.DeckBox).Include(p => p.Image).FirstOrDefaultAsync(p => p.Id == id && p.Deck.DeckBox.UserId==userId);
            if (card == null)
            {
                return View("AccessError"); 
            }
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Word,Defination,DeckId,UseExample,ShowCount,MoveDate,CreatedAt,UpdatedAt,Image")] Card card, int DeckId
            , IFormFile imageDb)
        {
            if (id != card.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                Image image = await _context.Images.FirstOrDefaultAsync(p => p.CardImageName == card.Image.CardImageName && p.CardId == card.Id);
                try
                {
                    if (imageDb != null)
                    {
                        List<Card> cards = _context.Cards.Where(p => p.Image.CardImageName == card.Image.CardImageName && p.Id != card.Id).ToList();
                        if (card.Image.CardImageName != null && cards.Count == 0)
                        {
                            string folderPathLstImg = Path.Combine(_webHostEnvironment.WebRootPath, "images", "card_images");
                            ImageAbillities.DeleteImage(card.Image.CardImageName, folderPathLstImg);
                            Image imageS = _context.Images.FirstOrDefault(p => p.CardId == card.Id && p.CardImageName == card.Image.CardImageName);
                            _context.Remove(imageS);
                            await _context.SaveChangesAsync();
                        }
                        string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "card_images");
                        var filename = ImageAbillities.UploadImage(imageDb, folderPath);
                        card.Image.CardImageName = filename;

                        card.DeckId = DeckId;
                        _context.Update(card);
                        await _context.SaveChangesAsync();

                    }

MemoryCards/Controllers/DecksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MemoryCards.Models;
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Localization;
namespace MemoryCards.Controllers
{
    [Authorize]
    public class DecksController : Controller
    {
        private readonly MemoryContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IStringLocalizer<DecksController> _localizer;

        public DecksController(MemoryContext context, IStringLocalizer<DecksController> localizer, UserManager<User> userManager)
        {
            _context = context;
            _localizer = localizer;
            _userManager = userManager;

        }

        public IActionResult Index(int? Id)
        {
            string userId =  _userManager.GetUserId(User);
            var deckBox = _context.DeckBoxes.FirstOrDefault(p => p.Id == Id);
            var deck = _context.Decks
                .Include(c => c.Cards)
                .Where(p => p.DeckBoxId == deckBox.Id && deckBox.UserId == userId)
                .OrderBy(c => c.RepeatDay);
            if(deck.Count()==0)
                return View("AccessError");
            return View(deck);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string userId = _userManager.GetUserId(User);
            var deck = await _context.Decks.FirstOrDefaultAsync(p=>p.Id==id && p.DeckBox.UserId == userId);
            
            if (deck == null)
            {
                return View("AccessError");
            }
            return View(deck);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RepeatDay,DeckBoxId,CreatedAt,UpdatedAt, LastSendMsgDate")] Deck deck)
        {
            if (id != deck.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var deckBox = _context.DeckBoxes
                        .AsNoTracking()
                        .Include(d => d.Decks)
                        .FirstOrDefault(p => p.Id == deck.DeckBoxId);
                    var check = deckBox.Decks.FirstOrDefault(c => c.RepeatDay == deck.RepeatDay);

                    if (check == null)
                    {
                        deck.LastSendMsgDate = DateTime.Now.AddDays(deck.RepeatDay);
                        _context.Update(deck);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                          TempData["deckerror"]=_localizer["deckError"]; 
                        return View(deck);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeckExists(deck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { Id = deck.DeckBoxId });
            }
            return View(deck);
        }

        private bool DeckExists(int id)
        {
            return _context.Decks.Any(e => e.Id == id);
        }
    }
}

MemoryCards/Views/Cards/Create.cshtml
@model MemoryCards.ViewModels.CardDeckViewModel

@{
    ViewData["Title"] = @Localizer["create_card"];
}

<h1>@Localizer["create_card"]</h1>

<hr />
<div class="row">
    
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="DeckId" value="@Model.Deck.Id" />
            <div class="group">
                <input asp-for="card.Word" type="text" required class="input" autocomplete="off" autofocus>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label class="label">@Localizer["word"]</label>
                <span asp-validation-for="card.Word" id="validWord" class="text-danger"></span>
            </div>
            <div class="group">
                <input asp-for="card.Defination" type="text" required class="input" autocomplete="off" autofocus>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label class="label">@Localizer["defination"]</label>
                <span asp-validation-for="card.Defination" id="validDefination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="desc" for="exampleFormControlTextarea1">@Localizer["use_example"]</label>
                <textarea asp-for="card.UseExample" class="form-control" id="exampleFormControlTextarea1" rows="3" autofocus></textarea>
                <span asp-validation-for="card.UseExample" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p class="imageName">@Localizer["imagecard"]</p>
                <label name="imageDb" class="file">
                    <input asp-for="card.Image.ImageFile" id="file" aria-label="File browser example" autofocus>
                    <span asp-validation-for="card.Image.ImageFile" class="file-custom"></span>
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["create"]" class="btn btn-light" autofocus/>
            </div>
        </form>
    </div>
</div>

<div>
    <a type="button" asp-action="Index" asp-controller="Cards" asp-route-id="@Model.Deck.Id" class="btn btn-light">@Localizer["back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MemoryCards/Views/Cards/Edit.cshtml
@model MemoryCards.Models.Card

@{
    ViewData["Title"] = @Localizer["edit_card"];
}

<h1>@Localizer["edit_card"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ShowCount" />
            <input type="hidden" asp-for="DeckId" />
            <input type="hidden" asp-for="@Model.Image.CardImageName" />
            <input type="hidden" asp-for="@Model.CreatedAt" />
            <div class="group">
                <input asp-for="Word" type="text" required class="input" autocomplete="off" autofocus>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label class="label">@Localizer["word"]</label>
                <span asp-validation-for="Word" id="validWord" class="text-danger"></span>
            </div>
            <div class="group">
                <input asp-for="Defination" type="text" required class="input" autocomplete="off" autofocus>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label class="label">@Localizer["defination"]</label>
                <span asp-validation-for="Defination" id="validDefination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="desc" for="exampleFormControlTextarea1">@Localizer["use_example"]</label>
                <textarea asp-for="UseExample" class="form-control" id="exampleFormControlTextarea1" rows="3" autofocus></textarea>
                <span asp-validation-for="UseExample" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p class="imageName">@Localizer["imagecard"]</p>
                <label name="imageDb" class="file">
                    <input type="file" name="imageDb" id="file" aria-label="File browser example" autofocus>
                    <span name="imageDb" class="file-custom"></span>
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["edit"]" class="btn btn-light" autofocus/>
            </div>
        </form>
    </div>
</div>

<div>
    <a type="button" asp-action="Index" asp-controller="Cards" asp-route-id="@Model.DeckId" class="btn btn-light">@Localizer["back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MemoryCards/Views/Cards/Index.cshtml
@model CardDeckViewModel

@{
    ViewData["Title"] = @Localizer["title"];
}
<body>
    <div class="slideshow-container" data-nextid="@ViewBag.Nextid">
        @foreach (var card in Model.Cards)
        {
            <div class="mySlides fade">
                <div class="card card-word cardsIndex" style="">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mr-5">
                        <a class="btn-sm button Delete" onclick="return confirm('@Localizer["deletejs"]')" asp-action="Delete" asp-route-id="@card.Id" id="#delete">
                            <i class="far fa-trash-alt"></i>
                        </a>
                        <a class="btn-sm ml-2 button" asp-action="Edit" asp-route-id="@card.Id">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                    </div>


                    <div class="card-body mb-4">
                        <div class="pb-3 cardWrapper">
                            <div class="cardContainer">
                                <div class="memoryCard mb-5">
                                    <div class="front" id="out">
                                        <span class="in card-word" style="word-break: break-all">@card.Word</span>
                                    </div>
                                    <div class="back" id="inner">
                                        <div class="content">
                                            @if (card.Image != null)
                                            {
                                                if (card.Image.CardImageName != null)
                                                {
                                                    <p class="Word" style="text-align: center;">@card.Defination</p>
                                                    <img class="cardTitle responsive" style="display: block; margin: auto" src="/images/card_images/@card.Image.CardImageName" alt="" height="280" />
                                                    <p class="Word" style="text-align: center;">@card.UseExample</p>
                                                    <br />

                                                }

                                            }
                                            else                                               
                                            {
                                            <p class="Word" style="text-align: center;">@Localizer["defination"]</p>
                                            <br />
                                            <p class="Word" style="text-align: center;">@card.Defination</p>
                                            <hr />
                                            <p class="Word" style="text-align: center;">@Localizer["use_example"]</p>
                                            <br />
                                            <p class="Word" style="text-align: center;">@card.UseExample</p>
                                            <hr />
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="myCarousel mb-5 mt-5">
                            <a type="button" style="float:left" id="@card.Id" class="btn ml-1 btn-danger btn-lg" asp-action="DontKnow" asp-route-id="@card.Id">@Localizer["dont_know"]</a>
                            <a type="button" style="float:right" id="@card.Id" class="btn btn-success btn-lg button" asp-action="Know" asp-route-id="@card.Id">@Localizer["know"]</a>
                        </div>
                    </div>
                </div>
            </div>
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        }

    </div>
    <br>

    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="card m-2 bg-light" style="height: 102px; text-align:center">
                <div class="card-body">
                    <a asp-action="Create" asp-route-id="@Model.DeckId"> <p class="card-title  position-relative CreateCard">+</p> </a>
                </div>
            </div>
        </div>

        @foreach (var card in Model.Cards)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="card m-2 bg-light" style="height: 102px; text-align:center">
                    <div class="card-body">
                        <h5 class="card-title position-relative">@card.Word</h5>
                    </div>
                </div>
            </div>
        }
    </div>


    <br>
    <a type="button" asp-controller="Decks" asp-action="Index" asp-route-id="@Model.Deck.DeckBoxId" class="btn btn-light">@Localizer["back"]</a>
</body>
<br>

@section Scripts {
    <script src="~/js/carouselCards.js" asp-append-version="true"></script>
    <script src="~/js/flipCards.js" asp-append-version="true"></script>
    <script src="~/js/cardIndex.js"></script>
    
}